app:
  jwt_secret: sso-server

server:
  http_port: 9090

database:
  host: 127.0.0.1
  port: 5432
  dbname: sso
  user: sso
  password: 123456
  sslmode: disable

redis:
  addr: 127.0.0.1:6379
  password:
  db:

email:
  from: no-reply@gethin.cn
  from_subject: Sso-server
  subject: Sso-server验证码

code:
  min: 100000
  max: 999999
  validity_period: 5
